name: Event
description: Create an event
title: "[Event]: "
labels: ["event"]
body:
  - type: input
    id: name
    attributes:
      label: Name
      description: What is the name of this event?
    validations:
      required: true
  - type: input
    id: venue
    attributes:
      label: Venue
      description: What is the name of the venue?
    validations:
      required: true
  - type: input
    id: city
    attributes:
      label: City
      description: What city is the venue located?
    validations:
      required: true
  - type: input
    id: date
    attributes:
      label: Date
      description: What date do you want to hold the event?
    validations:
      required: true
  - type: input
    id: time
    attributes:
      label: Time
      description: What time do you want to start the event?
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: Link
      description: Please add a link (google maps, yelp, etc.) to make it easier to find for others.
    validations:
      required: true
