name: "Update events in readme"

on:
  issues:
    types:
      - opened
      - edited
      - closed
      - reopened
      - labeled
      - unlabeled

  # every day at 4am pacific time
  schedule:
    - cron: "0 12 * * *"

  workflow_dispatch: {}

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: nix setup
        uses: DeterminateSystems/nix-installer-action@main

      - name: cache nix setup
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: build node modules
        run: |
          nix build .#eventModules
          cp -r result/node_modules .

      - name: run script
        run: |
          nix run nixpkgs#nodejs -- .github/actions/update-upcoming-events/script.js
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          REPOSITORY_NAME: ${{ github.event.repository.name }}
